"""
Vouch — Seed & Fallback PR Catalogs.

Separated from web routing and scoring logic to keep dashboard/app.py clean,
production-level, and ready for AWS services integration.
"""

from __future__ import annotations

REPO_SPECIFIC_PR_SPECS: dict[str, dict] = {
    "facebook/react": {
        "base_num": 31200,
        "items": [
            ("[ACTIVE] Fix useActionState transition cancellation during high priority updates", "packages/react-reconciler/src/ReactFiberWorkLoop.js", "open", 1, 380, 95, "acdlite", "sebmarkbage", "high", 0, 45),
            ("Refactor Server Components flight protocol buffer deserializer", "packages/react-client/src/ReactFlightClient.js", "closed", 2, 620, 180, "sebmarkbage", "acdlite", "high", 1, 90),
            ("Deprecate legacy context fallback in developmental fiber validation", "packages/react/src/ReactContext.js", "closed", 3, 95, 40, "gaearon", "sophiebits", "low", 4, 7200),
            ("[ACTIVE] Optimize compiler memoization bailout for inline closure props", "compiler/packages/babel-plugin-react-compiler/src/HIR/BuildHIR.ts", "open", 4, 480, 130, "josephsavona", "mvitousek", "medium", 2, 1800),
            ("Fix hydration mismatch warning formatting when dom nesting is invalid", "packages/react-dom/src/client/ReactDOMComponent.js", "closed", 5, 120, 50, "sophiebits", "rickhanlonii", "low", 5, 5400),
            ("Prevent memory leak in Suspense hydration boundary timeout fallback", "packages/react-reconciler/src/ReactFiberHydrationContext.js", "closed", 6, 440, 110, "acdlite", "bvaughn", "high", 0, 60),
            ("[ACTIVE] Support View Transitions API in React DOM root concurrent render", "packages/react-dom/src/client/ReactDOMRoot.js", "open", 7, 310, 80, "rickhanlonii", "acdlite", "medium", 3, 2400),
            ("Fix useId collision in concurrent server rendering with stream chunks", "packages/react-server/src/ReactServerStream.js", "closed", 8, 290, 70, "sebmarkbage", "gnoff", "high", 1, 85),
            ("Update documentation and release notes for React 19.1 RC", "README.md", "closed", 9, 45, 10, "trueadm", "gaearon", "low", 1, 9000),
            ("[ACTIVE] Improve error boundary recovery retry semantics in act() environment", "packages/react-reconciler/src/ReactFiberErrorLogger.js", "open", 10, 210, 55, "eps1lon", "sophiebits", "medium", 2, 3600),
            ("Optimize JSX element creation runtime allocations in dev environment", "packages/react/src/jsx/ReactJSXElement.js", "closed", 11, 160, 45, "gnoff", "sebmarkbage", "low", 3, 4800),
            ("Sanitize synthetic event dispatch loop against detached iframe access", "packages/react-dom/src/events/DOMPluginEventSystem.js", "closed", 12, 350, 90, "necolas", "acdlite", "high", 0, 70),
            ("[ACTIVE] Add micro-benchmark suite for concurrent transition scheduler", "fixtures/flight/src/index.js", "open", 13, 190, 30, "bvaughn", "josephsavona", "low", 2, 4200),
            ("Fix useEffect cleanup ordering when parent and child unmount simultaneously", "packages/react-reconciler/src/ReactFiberCommitWork.js", "closed", 14, 275, 65, "acdlite", "sebmarkbage", "medium", 3, 3100),
            ("[ACTIVE] Propagate async server action context across flight stream boundaries", "packages/react-server/src/ReactFlightServer.js", "open", 16, 510, 140, "sebmarkbage", "acdlite", "high", 1, 110),
            ("Clarify Server Actions form state documentation and examples", "docs/server-actions.md", "closed", 18, 55, 12, "rickhanlonii", "gaearon", "low", 2, 6000),
            ("Fix stale closure in useSyncExternalStore during concurrent re-renders", "packages/react-reconciler/src/ReactFiberHooks.js", "closed", 20, 240, 60, "trueadm", "acdlite", "medium", 3, 2700),
            ("[ACTIVE] Implement Fast Refresh support for React Compiler transformed hooks", "packages/react-refresh/src/ReactFreshRuntime.js", "open", 22, 330, 85, "josephsavona", "mvitousek", "medium", 2, 2100),
            ("Fix DOM node reference retention in synthetic clipboard event pool", "packages/react-dom/src/events/SyntheticEvent.js", "closed", 24, 130, 35, "sophiebits", "rickhanlonii", "low", 4, 5000),
            ("Refactor lane priority calculation for continuous input events", "packages/react-reconciler/src/ReactFiberLane.js", "closed", 26, 380, 95, "acdlite", "sebmarkbage", "medium", 4, 3800),
            ("[ACTIVE] Add trace measurement marks for DevTools interaction timelines", "packages/react-devtools-shared/src/devtools.js", "open", 28, 145, 40, "bvaughn", "acdlite", "low", 1, 4600),
            ("Fix passive effect destruction loop on aborted unmount transitions", "packages/react-reconciler/src/ReactFiberWorkLoop.js", "closed", 30, 420, 105, "sebmarkbage", "acdlite", "high", 0, 50),
            ("Normalize CSS style property vendor prefix capitalization in ReactDOM", "packages/react-dom/src/shared/CSSPropertyOperations.js", "closed", 33, 85, 20, "gaearon", "sophiebits", "low", 3, 7200),
            ("[ACTIVE] Support streaming async iterables in React Server Components response", "packages/react-server/src/ReactServerStreamConfigNode.js", "open", 36, 490, 125, "gnoff", "sebmarkbage", "medium", 3, 2900),
            ("Fix focus restoration failure when unmounting modal portals", "packages/react-dom/src/client/ReactDOMHostConfig.js", "closed", 40, 175, 45, "rickhanlonii", "acdlite", "medium", 2, 3300),
            ("Update Flow type definitions for Activity and SuspenseList components", "packages/react/src/ReactActivity.js", "closed", 45, 60, 15, "trueadm", "sophiebits", "low", 2, 5900),
            ("Fix offscreen component display style toggle during hydration", "packages/react-reconciler/src/ReactFiberCompleteWork.js", "closed", 52, 230, 60, "acdlite", "sebmarkbage", "medium", 3, 3500),
            ("Deprecate legacy string ref warnings in production build pipelines", "packages/react/src/ReactElement.js", "closed", 60, 40, 10, "gaearon", "rickhanlonii", "low", 2, 8000),
        ]
    },
    "pallets/flask": {
        "base_num": 5480,
        "items": [
            ("[ACTIVE] Sanitize session cookie domain validation to prevent subdomain fixation", "src/flask/sessions.py", "open", 1, 310, 75, "davidism", "pgjones", "high", 0, 40),
            ("Fix context locals leak when handling streaming generator response exceptions", "src/flask/ctx.py", "closed", 2, 450, 110, "pgjones", "davidism", "high", 1, 80),
            ("Clarify blueprint url_prefix precedence in nested registration docs", "docs/blueprints.rst", "closed", 3, 35, 10, "pallets-bot", "davidism", "low", 3, 7200),
            ("[ACTIVE] Add support for async signals dispatch with blinker 1.9+", "src/flask/signals.py", "open", 4, 220, 50, "pgjones", "untitaker", "medium", 2, 1900),
            ("Allow custom JSON decoder instance in app.json.loads override", "src/flask/json/provider.py", "closed", 5, 85, 20, "untitaker", "davidism", "low", 4, 5200),
            ("Fix secret key rotation fallback during session decryption", "src/flask/sessions.py", "closed", 6, 380, 90, "davidism", "pgjones", "high", 0, 55),
            ("[ACTIVE] Optimize route matching trie cache for repeated dynamic url lookups", "src/flask/routing.py", "open", 7, 260, 65, "davidism", "untitaker", "medium", 3, 2500),
            ("Ensure teardown_appcontext executes reliably on unhandled worker timeouts", "src/flask/app.py", "closed", 8, 340, 85, "mitsuhiko", "davidism", "high", 1, 95),
            ("Update tutorial on application factories and blueprint patterns", "docs/tutorial/factory.rst", "closed", 9, 45, 12, "pallets-bot", "davidism", "low", 2, 8500),
            ("[ACTIVE] Support Werkzeug 3.1 HTTP range request handling for send_file", "src/flask/helpers.py", "open", 10, 180, 40, "davidism", "pgjones", "medium", 2, 3200),
            ("Refactor CLI click runner to preserve custom logging configurations", "src/flask/cli.py", "closed", 11, 140, 35, "untitaker", "davidism", "low", 3, 4400),
            ("Prevent host header poisoning in url_for external URL generation", "src/flask/helpers.py", "closed", 12, 290, 70, "pgjones", "davidism", "high", 0, 65),
            ("[ACTIVE] Add pytest fixture helper for async test client request dispatch", "src/flask/testing.py", "open", 13, 175, 30, "davidism", "pgjones", "low", 2, 3800),
            ("Fix blueprint static folder resolution when package has nested namespace", "src/flask/blueprints.py", "closed", 14, 210, 55, "davidism", "untitaker", "medium", 3, 2800),
            ("[ACTIVE] Sanitize redirect parameter in abort(302) to prevent open redirects", "src/flask/helpers.py", "open", 16, 320, 80, "pgjones", "davidism", "high", 1, 105),
            ("Clarify request lifecycle hooks execution order in documentation", "docs/lifecycle.rst", "closed", 18, 50, 15, "pallets-bot", "davidism", "low", 2, 6200),
            ("Fix JSONProvider date formatting when timezone aware datetimes are dumped", "src/flask/json/provider.py", "closed", 20, 115, 25, "untitaker", "davidism", "low", 3, 4900),
            ("[ACTIVE] Implement streaming response chunk cancellation when client disconnects", "src/flask/wrappers.py", "open", 22, 275, 70, "davidism", "pgjones", "medium", 3, 2200),
            ("Preserve custom exception handler response headers on unhandled errors", "src/flask/app.py", "closed", 24, 160, 40, "mitsuhiko", "davidism", "medium", 2, 3600),
            ("Optimize url_rule map compilation for large route tables", "src/flask/routing.py", "closed", 26, 310, 85, "davidism", "untitaker", "medium", 3, 2900),
            ("Update quickstart installation guide for Python 3.13 support", "docs/quickstart.rst", "closed", 28, 40, 8, "pallets-bot", "davidism", "low", 1, 8800),
            ("[ACTIVE] Support ASGI lifespan protocol in Flask run development server", "src/flask/cli.py", "open", 30, 240, 60, "pgjones", "davidism", "medium", 2, 2700),
            ("Fix template reload detection when templates directory is a symlink", "src/flask/templating.py", "closed", 33, 95, 20, "untitaker", "davidism", "low", 2, 5400),
            ("Refactor config.from_prefixed_env to parse nested JSON environment variables", "src/flask/config.py", "closed", 36, 185, 45, "davidism", "pgjones", "medium", 3, 3100),
            ("[ACTIVE] Add diagnostic telemetry hook for slow template renders", "src/flask/signals.py", "open", 40, 150, 35, "mitsuhiko", "davidism", "low", 1, 4100),
            ("Fix cookie SameSite=None attribute stripping on insecure transport", "src/flask/sessions.py", "closed", 45, 205, 50, "pgjones", "davidism", "medium", 2, 3400),
            ("Update typing annotations for custom Response and Request subclasses", "src/flask/typing.py", "closed", 52, 130, 30, "davidism", "untitaker", "low", 3, 6500),
            ("Deprecate legacy locked cached property helper in favor of standard functools", "src/flask/helpers.py", "closed", 60, 45, 12, "pallets-bot", "davidism", "low", 2, 7800),
        ]
    },
    "kubernetes/kubernetes": {
        "base_num": 128540,
        "items": [
            ("[ACTIVE] Fix retry backoff overflow in scheduler pod binding", "pkg/scheduler/binding.go", "open", 1, 420, 95, "aojea", "thockin", "high", 0, 50),
            ("Add token refresh grace period to API server auth middleware", "pkg/kubeapiserver/authenticator/token.go", "closed", 2, 510, 120, "dims", "deads2k", "high", 1, 85),
            ("Update kubectl describe node formatting for non-root containers", "pkg/kubectl/cmd/describe.go", "closed", 3, 40, 10, "k8s-ci-robot", "soltysh", "low", 4, 8000),
            ("[ACTIVE] Cgroup v2 memory throttling enforcement in Kubelet container manager", "pkg/kubelet/cm/cgroup_manager_linux.go", "open", 4, 380, 90, "mrunalp", "thockin", "high", 0, 65),
            ("Refactor lease controller renewal loop to use jittered backoff", "pkg/controller/lease/lease_controller.go", "closed", 5, 230, 55, "wojtek-t", "liggitt", "medium", 3, 2600),
            ("Fix admission webhook timeout escalation during master failover", "pkg/controlplane/apiserver.go", "closed", 6, 460, 115, "liggitt", "deads2k", "high", 1, 90),
            ("[ACTIVE] Optimize pod scheduling preemption queue lock contention", "pkg/scheduler/framework/plugins/defaultpreemption.go", "open", 7, 340, 80, "cheftako", "aojea", "medium", 2, 2300),
            ("Fix secret decryption cache invalidation when KMS plugin rotates keys", "pkg/kubeapiserver/authenticator/kms.go", "closed", 8, 395, 95, "deads2k", "liggitt", "high", 0, 55),
            ("Clarify PodDisruptionBudget uncounted terms in user documentation", "docs/concepts/workloads/pods/disruptions.md", "closed", 9, 50, 15, "k8s-ci-robot", "soltysh", "low", 2, 9200),
            ("[ACTIVE] Support dual-stack IPv6 multicast routes in kube-proxy nftables backend", "pkg/proxy/nftables/proxier.go", "open", 10, 480, 130, "thockin", "aojea", "medium", 3, 3100),
            ("Prevent goroutine leak in watch stream keepalive channel on client terminate", "staging/src/k8s.io/client-go/rest/request.go", "closed", 11, 210, 45, "wojtek-t", "dims", "medium", 3, 2800),
            ("Sanitize node name input in CSI volume attachment authorization checks", "pkg/volume/csi/csi_attacher.go", "closed", 12, 330, 75, "liggitt", "thockin", "high", 0, 75),
            ("[ACTIVE] Add e2e conformance tests for dynamic resource allocation (DRA)", "test/e2e/dra/dra.go", "open", 13, 290, 40, "pohly", "cheftako", "low", 2, 4500),
            ("Fix Kubelet volume unmount deadlock when pod teardown races container exit", "pkg/kubelet/volumemanager/reconciler/reconciler.go", "closed", 14, 370, 85, "jsafrane", "thockin", "medium", 3, 2900),
            ("[ACTIVE] Enforce PodSecurity admission audit annotations on subresource updates", "pkg/security/podsecurity/admission.go", "open", 16, 260, 60, "tallclair", "liggitt", "medium", 2, 2400),
            ("Update kubeadm init phases documentation for custom etcd clusters", "docs/setup/production-environment/tools/kubeadm/init-phases.md", "closed", 18, 45, 12, "neolit123", "k8s-ci-robot", "low", 1, 7500),
            ("Fix resource quota calculation for ephemeral storage in init containers", "pkg/quota/v1/evaluator/core/pods.go", "closed", 20, 190, 45, "derekwaynecarr", "soltysh", "low", 3, 4900),
            ("[ACTIVE] Support user namespaces in containerd runtime handler via Kubelet CRI", "pkg/kubelet/kuberuntime/kuberuntime_container.go", "open", 22, 520, 140, "mrunalp", "dims", "medium", 3, 3300),
            ("Fix etcd client dialer connection leak during rapid endpoint healthchecks", "staging/src/k8s.io/apiserver/pkg/storage/etcd3/compact.go", "closed", 24, 280, 65, "wojtek-t", "liggitt", "medium", 2, 3100),
            ("Refactor horizontal pod autoscaler stabilization window calculation", "pkg/controller/podautoscaler/horizontal.go", "closed", 26, 240, 50, "maciekpytel", "soltysh", "low", 3, 5200),
            ("Update metric descriptions in kube-scheduler prometheus registry", "pkg/scheduler/metrics/metrics.go", "closed", 28, 65, 15, "cheftako", "k8s-ci-robot", "low", 1, 8600),
            ("[ACTIVE] Handle graceful node shutdown cancellation when systemd inhibitor fails", "pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go", "open", 30, 310, 70, "bswartz", "mrunalp", "medium", 2, 2800),
            ("Fix service account token projected volume permission mode in SELinux", "pkg/kubelet/token/token_manager.go", "closed", 33, 225, 55, "tallclair", "liggitt", "medium", 3, 3400),
            ("Optimize memory allocations in apiserver JSON deserialization fast-path", "staging/src/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go", "closed", 36, 350, 90, "wojtek-t", "dims", "medium", 3, 3000),
            ("Fix client-go exponential backoff reset on transient 429 TooManyRequests", "staging/src/k8s.io/client-go/util/retry/util.go", "closed", 40, 140, 30, "liggitt", "wojtek-t", "low", 2, 6000),
            ("Update code generator scripts for Kubernetes API v1.33 types", "hack/update-codegen.sh", "closed", 45, 80, 25, "sttts", "k8s-ci-robot", "low", 1, 7900),
            ("[ACTIVE] Implement topology-aware volume binding delay timeout in scheduler", "pkg/scheduler/framework/plugins/volumetopology/volume_topology.go", "open", 52, 280, 65, "jsafrane", "cheftako", "medium", 2, 2700),
            ("Deprecate legacy cloud provider flag in kubelet arguments parsing", "cmd/kubelet/app/options/options.go", "closed", 60, 50, 15, "dims", "thockin", "low", 2, 8500),
        ]
    },
    "fastapi/fastapi": {
        "base_num": 11580,
        "items": [
            ("[ACTIVE] Sanitize OAuth2 password bearer token validation against timing attacks", "fastapi/security/oauth2.py", "open", 1, 290, 65, "tiangolo", "Kludex", "high", 0, 40),
            ("Fix OpenAPI schema generation for Union types in Pydantic v2 nested models", "fastapi/openapi/utils.py", "closed", 2, 380, 95, "tiangolo", "dmontagu", "medium", 2, 2100),
            ("Update tutorial on OAuth2 password flow with JWT tokens expiration", "docs/en/docs/tutorial/security/oauth2-jwt.md", "closed", 3, 45, 12, "tiangolo", "yezz123", "low", 4, 8200),
            ("[ACTIVE] Fix dependency yield generator cleanup on client disconnect during streaming", "fastapi/dependencies/utils.py", "open", 4, 410, 105, "Kludex", "tiangolo", "high", 0, 55),
            ("Add background task exception logging when using custom lifespan handler", "fastapi/applications.py", "closed", 5, 175, 40, "Kludex", "tiangolo", "low", 3, 5600),
            ("Prevent memory leak in custom response encoder when handling circular references", "fastapi/encoders.py", "closed", 6, 360, 85, "dmontagu", "tiangolo", "high", 1, 85),
            ("[ACTIVE] Optimize route matching and parameter parsing for WebSocket endpoints", "fastapi/routing.py", "open", 7, 280, 70, "tiangolo", "Kludex", "medium", 2, 2400),
            ("Fix CORS preflight response headers omission on 401 Unauthorized exceptions", "fastapi/middleware/cors.py", "closed", 8, 320, 75, "yezz123", "tiangolo", "high", 0, 65),
            ("Clarify dependency overrides in test client documentation", "docs/en/docs/advanced/testing-dependencies.md", "closed", 9, 50, 15, "tiangolo", "dmontagu", "low", 2, 7900),
            ("[ACTIVE] Support PEP 695 type alias syntax in response_model annotations", "fastapi/dependencies/models.py", "open", 10, 240, 55, "dmontagu", "Kludex", "medium", 3, 2900),
            ("Preserve custom status code on HTTPException subclasses in exception handlers", "fastapi/exception_handlers.py", "closed", 11, 130, 30, "Kludex", "tiangolo", "low", 3, 4900),
            ("Fix security scope verification bypass in nested security dependencies", "fastapi/security/base.py", "closed", 12, 310, 70, "tiangolo", "Kludex", "high", 1, 95),
            ("[ACTIVE] Add automated benchmark suite for Starlette ASGI request dispatch", "benchmarks/test_routing.py", "open", 13, 190, 35, "yezz123", "tiangolo", "low", 1, 4100),
            ("Fix request body validation error response formatting for bulk JSON array", "fastapi/dependencies/utils.py", "closed", 14, 220, 50, "dmontagu", "tiangolo", "medium", 2, 2800),
            ("[ACTIVE] Sanitize header values in redirect responses against CRLF injection", "fastapi/responses.py", "open", 16, 295, 65, "Kludex", "tiangolo", "high", 0, 50),
            ("Update tutorial on background tasks and Celery integration patterns", "docs/en/docs/tutorial/background-tasks.md", "closed", 18, 55, 10, "tiangolo", "yezz123", "low", 2, 6500),
            ("Fix form-data file upload temporary file descriptor leak on aborted request", "fastapi/datastructures.py", "closed", 20, 260, 60, "tiangolo", "Kludex", "medium", 3, 3100),
            ("[ACTIVE] Support Pydantic v2 computed_field serialization in response models", "fastapi/openapi/models.py", "open", 22, 310, 75, "dmontagu", "tiangolo", "medium", 2, 2600),
            ("Normalize swagger-ui CDN asset bundle fallback URLs", "fastapi/openapi/docs.py", "closed", 24, 75, 18, "yezz123", "tiangolo", "low", 3, 5300),
            ("Optimize dependency injection tree resolution caching across concurrent requests", "fastapi/routing.py", "closed", 26, 340, 80, "tiangolo", "dmontagu", "medium", 3, 3200),
            ("Add typing hints for lifespan state context management", "fastapi/applications.py", "closed", 28, 110, 25, "Kludex", "tiangolo", "low", 2, 5800),
            ("[ACTIVE] Support streaming JSON response formatting with custom encoders", "fastapi/responses.py", "open", 30, 250, 55, "tiangolo", "Kludex", "medium", 2, 2500),
            ("Fix path parameter regex pattern escaping in OpenAPI schema generation", "fastapi/openapi/utils.py", "closed", 33, 140, 35, "dmontagu", "tiangolo", "low", 2, 4700),
            ("Refactor query parameter default value unwrapping for Optional types", "fastapi/dependencies/utils.py", "closed", 36, 185, 45, "Kludex", "tiangolo", "medium", 3, 3000),
            ("Update quickstart tutorial on async database sessions with SQLAlchemy 2.0", "docs/en/docs/tutorial/sql-databases.md", "closed", 40, 65, 15, "tiangolo", "yezz123", "low", 2, 7500),
            ("Fix Cookie parameter SameSite handling in security schemes", "fastapi/security/api_key.py", "closed", 45, 215, 50, "tiangolo", "Kludex", "medium", 2, 3300),
            ("Deprecate legacy WSGIMiddleware import path in favor of a2wsgi recommendation", "fastapi/middleware/wsgi.py", "closed", 52, 40, 10, "Kludex", "tiangolo", "low", 2, 8200),
            ("Clarify OAuth2 refresh token flow recommendations in official docs", "docs/en/docs/tutorial/security/oauth2-jwt.md", "closed", 60, 45, 12, "yezz123", "tiangolo", "low", 1, 8800),
        ]
    },
    "psf/requests": {
        "base_num": 6740,
        "items": [
            ("[ACTIVE] Fix proxy authorization header stripping on HTTPS to HTTP redirect downgrade", "src/requests/sessions.py", "open", 1, 310, 70, "sigmavirus24", "sethmlarson", "high", 0, 45),
            ("Bump urllib3 compatibility matrix and patch chunked transfer boundary", "src/requests/adapters.py", "closed", 2, 280, 60, "sethmlarson", "nateprewitt", "medium", 2, 2300),
            ("Fix RequestsCookieJar.popitem() key-value tuple unpacking under Python 3.13", "src/requests/cookies.py", "closed", 3, 40, 10, "nateprewitt", "sigmavirus24", "low", 4, 7600),
            ("[ACTIVE] Prevent SSL connection reuse after cert validation failure in HTTPAdapter", "src/requests/adapters.py", "open", 4, 380, 90, "sethmlarson", "sigmavirus24", "high", 0, 50),
            ("Add SSL verification troubleshooting guide to official docs", "docs/user/advanced.rst", "closed", 5, 75, 15, "kennethreitz", "nateprewitt", "low", 3, 8500),
            ("Fix Digest auth nonce count cache race condition under high concurrency", "src/requests/auth.py", "closed", 6, 340, 80, "sigmavirus24", "sethmlarson", "high", 1, 85),
            ("[ACTIVE] Optimize connection pool retry backoff calculation for 503 responses", "src/requests/adapters.py", "open", 7, 210, 45, "sethmlarson", "nateprewitt", "medium", 2, 2700),
            ("Prevent credentials leak in Authorization header during cross-origin redirects", "src/requests/sessions.py", "closed", 8, 360, 85, "sigmavirus24", "lukasa", "high", 0, 60),
            ("Clarify prepared request body serialization in developer docs", "docs/dev/internals.rst", "closed", 9, 45, 10, "kennethreitz", "sigmavirus24", "low", 2, 9000),
            ("[ACTIVE] Support custom SSLContext ALPN protocols negotiation in adapter", "src/requests/adapters.py", "open", 10, 260, 60, "sethmlarson", "sigmavirus24", "medium", 3, 3100),
            ("Refactor hooks dispatch to preserve custom response hook modifications", "src/requests/hooks.py", "closed", 11, 120, 25, "nateprewitt", "sethmlarson", "low", 3, 5100),
            ("Fix stream response socket leak when Response.close() is not called in generator", "src/requests/models.py", "closed", 12, 330, 75, "lukasa", "sigmavirus24", "high", 1, 95),
            ("[ACTIVE] Add automated integration tests for HTTP proxy basic auth against squid", "tests/test_proxy.py", "open", 13, 180, 30, "nateprewitt", "sethmlarson", "low", 2, 4200),
            ("Fix urllib3 pool cleanup when Session is closed in separate worker thread", "src/requests/sessions.py", "closed", 14, 240, 55, "sethmlarson", "sigmavirus24", "medium", 2, 2900),
            ("[ACTIVE] Sanitize URL fragments before sending HTTP/1.1 request line", "src/requests/models.py", "open", 16, 290, 65, "sigmavirus24", "sethmlarson", "high", 0, 55),
            ("Update quickstart session usage examples in official documentation", "docs/user/quickstart.rst", "closed", 18, 50, 12, "kennethreitz", "nateprewitt", "low", 2, 6800),
            ("Fix content-type header overwrite when sending multipart/form-data with custom boundary", "src/requests/models.py", "closed", 20, 190, 40, "nateprewitt", "sigmavirus24", "medium", 3, 3300),
            ("[ACTIVE] Support Brotli content encoding decompression in response stream", "src/requests/adapters.py", "open", 22, 275, 65, "sethmlarson", "nateprewitt", "medium", 2, 2500),
            ("Preserve custom certifi trust store path when REQUESTS_CA_BUNDLE is set", "src/requests/certs.py", "closed", 24, 85, 20, "sethmlarson", "sigmavirus24", "low", 3, 5400),
            ("Optimize headers case-insensitive dict lookups with string intern caching", "src/requests/structures.py", "closed", 26, 210, 50, "lukasa", "nateprewitt", "medium", 3, 3100),
            ("Update test suite dependencies and CI matrix for Python 3.14 alpha", ".github/workflows/tests.yml", "closed", 28, 60, 15, "nateprewitt", "sethmlarson", "low", 1, 8400),
            ("[ACTIVE] Fix response iter_lines chunk splitting on multi-byte UTF-8 boundaries", "src/requests/models.py", "open", 30, 230, 50, "sigmavirus24", "sethmlarson", "medium", 2, 2700),
            ("Fix cookie expiration timestamp comparison with local system clock offset", "src/requests/cookies.py", "closed", 33, 115, 25, "nateprewitt", "sigmavirus24", "low", 2, 4800),
            ("Refactor status code lookup dictionary to include HTTP 425 and 451", "src/requests/status_codes.py", "closed", 36, 70, 15, "kennethreitz", "nateprewitt", "low", 2, 6200),
            ("[ACTIVE] Handle graceful connection termination on HTTP 504 Gateway Timeout", "src/requests/adapters.py", "open", 40, 260, 55, "sethmlarson", "sigmavirus24", "medium", 2, 2900),
            ("Fix urllib3 redirect history preservation in Response.history tuple", "src/requests/sessions.py", "closed", 45, 175, 40, "sigmavirus24", "nateprewitt", "medium", 2, 3400),
            ("Update contributor guidelines for security vulnerability disclosures", "SECURITY.md", "closed", 52, 35, 8, "sigmavirus24", "sethmlarson", "low", 1, 9500),
            ("Deprecate legacy internal request encoding fallback warnings", "src/requests/packages.py", "closed", 60, 40, 10, "nateprewitt", "sigmavirus24", "low", 2, 8900),
        ]
    }
}

DEMO_PRS: list[dict] = [
    {
        "pr_key": "kubernetes/kubernetes#128540",
        "pr_url": "https://github.com/kubernetes/kubernetes/pull/128540",
        "repo": "kubernetes/kubernetes",
        "pr_number": 128540,
        "title": "Fix retry backoff overflow in scheduler pod binding",
        "author": "aojea",
        "reviewer": "thockin",
        "state": "open",
        "created_at": "2026-09-17T08:30:00Z",
        "merged_at": None,
        "change_risk": 0.81,
        "review_confidence": 0.23,
        "residual_risk": 0.62,
        "depth_score": 0.15,
        "attention_state": 0.38,
        "time_adequacy": 0.22,
        "reviewer_familiarity": 0.70,
        "status": "re_queued",
        "re_queued": True,
        "explanation": (
            "Approved in 73s on a 520-line diff touching "
            "`pkg/scheduler/binding.go` — a file with 8 reverts in 90 days — "
            "by a reviewer 6 reviews into a session; recommend re-review of "
            "the exponential backoff boundary conditions."
        ),
        "top_features": [
            {"feature": "total_revert_count", "contribution": 0.312},
            {"feature": "path_infra", "contribution": 0.228},
            {"feature": "lines_added", "contribution": 0.181},
        ],
        "comments": [
            {"body": "LGTM", "class_name": "rubber_stamp", "weight": 0.0, "path": None},
        ],
        "diff_lines": 520,
        "review_duration_seconds": 73,
        "consecutive_reviews": 6,
        "additions": 420,
        "deletions": 100,
        "changed_files": 4,
        "sensitive_files": [],
        "live": False,
    },
    {
        "pr_key": "kubernetes/kubernetes#128201",
        "pr_url": "https://github.com/kubernetes/kubernetes/pull/128201",
        "repo": "kubernetes/kubernetes",
        "pr_number": 128201,
        "title": "Add token refresh grace period to API server auth middleware",
        "author": "dims",
        "reviewer": "deads2k",
        "state": "open",
        "created_at": "2026-09-17T06:15:00Z",
        "merged_at": None,
        "change_risk": 0.88,
        "review_confidence": 0.41,
        "residual_risk": 0.52,
        "depth_score": 0.45,
        "attention_state": 0.55,
        "time_adequacy": 0.38,
        "reviewer_familiarity": 0.85,
        "status": "re_queued",
        "re_queued": True,
        "explanation": (
            "A 340-line auth middleware change received only one clarifying "
            "question in 4 minutes from a reviewer mid-session; request explicit "
            "sign-off on the token expiry boundary before merging to main."
        ),
        "top_features": [
            {"feature": "path_auth", "contribution": 0.445},
            {"feature": "mean_defect_density", "contribution": 0.289},
            {"feature": "total_revert_count", "contribution": 0.201},
        ],
        "comments": [
            {"body": "Why is the grace period 30s and not configurable?", "class_name": "clarifying", "weight": 0.45, "path": "staging/src/k8s.io/apiserver/pkg/authentication/token/cache/caching_token_authenticator.go"},
        ],
        "diff_lines": 340,
        "review_duration_seconds": 247,
        "consecutive_reviews": 3,
        "additions": 290,
        "deletions": 50,
        "changed_files": 3,
        "sensitive_files": ["staging/src/k8s.io/apiserver/pkg/authentication/token/cache/caching_token_authenticator.go"],
        "live": False,
    },
    {
        "pr_key": "kubernetes/kubernetes#127998",
        "pr_url": "https://github.com/kubernetes/kubernetes/pull/127998",
        "repo": "kubernetes/kubernetes",
        "pr_number": 127998,
        "title": "Update kubeadm certs rotation to use new crypto primitives",
        "author": "pacoxu",
        "reviewer": "neolit123",
        "state": "closed",
        "created_at": "2026-09-12T14:00:00Z",
        "merged_at": "2026-09-12T16:44:00Z",
        "change_risk": 0.79,
        "review_confidence": 0.62,
        "residual_risk": 0.30,
        "depth_score": 0.72,
        "attention_state": 0.78,
        "time_adequacy": 0.55,
        "reviewer_familiarity": 0.90,
        "status": "closed",
        "re_queued": False,
        "explanation": (
            "A 280-line crypto rotation change received two security-class "
            "comments in 18 minutes from a reviewer familiar with the certs "
            "package; confidence is adequate and no re-review required."
        ),
        "top_features": [
            {"feature": "path_crypto", "contribution": 0.398},
            {"feature": "mean_defect_density", "contribution": 0.231},
            {"feature": "files_touched", "contribution": 0.187},
        ],
        "comments": [
            {"body": "This key size must match the CA config — verify RSA 4096 is enforced downstream.", "class_name": "security", "weight": 1.0, "path": "cmd/kubeadm/app/util/pkiutil/pki_helpers.go"},
            {"body": "The rotation window check will fail for certs expiring exactly at midnight UTC — off-by-one.", "class_name": "logic_concern", "weight": 0.8, "path": "cmd/kubeadm/app/phases/certs/renewal/manager.go"},
        ],
        "diff_lines": 280,
        "review_duration_seconds": 1082,
        "consecutive_reviews": 1,
        "additions": 220,
        "deletions": 60,
        "changed_files": 5,
        "sensitive_files": ["cmd/kubeadm/app/util/pkiutil/pki_helpers.go"],
        "live": False,
    },
    {
        "pr_key": "kubernetes/kubernetes#127654",
        "pr_url": "https://github.com/kubernetes/kubernetes/pull/127654",
        "repo": "kubernetes/kubernetes",
        "pr_number": 127654,
        "title": "Fix typos in docs/concepts/workloads/pods.md",
        "author": "windsonsea",
        "reviewer": "tengqm",
        "state": "closed",
        "created_at": "2026-09-11T10:00:00Z",
        "merged_at": "2026-09-11T11:22:00Z",
        "change_risk": 0.04,
        "review_confidence": 0.88,
        "residual_risk": 0.005,
        "depth_score": 0.60,
        "attention_state": 0.91,
        "time_adequacy": 0.90,
        "reviewer_familiarity": 0.60,
        "status": "closed",
        "re_queued": False,
        "explanation": (
            "A 12-line documentation typo fix received careful review with "
            "two style suggestions; change risk is negligible and no action needed."
        ),
        "top_features": [
            {"feature": "lines_added", "contribution": 0.020},
            {"feature": "diff_uniformity", "contribution": 0.010},
            {"feature": "files_touched", "contribution": 0.008},
        ],
        "comments": [
            {"body": "s/occured/occurred", "class_name": "nit_style", "weight": 0.15, "path": "docs/concepts/workloads/pods.md"},
            {"body": "Remove trailing whitespace on line 42", "class_name": "nit_style", "weight": 0.15, "path": "docs/concepts/workloads/pods.md"},
        ],
        "diff_lines": 12,
        "review_duration_seconds": 95,
        "consecutive_reviews": 0,
        "additions": 8,
        "deletions": 4,
        "changed_files": 1,
        "sensitive_files": [],
        "live": False,
    },
    {
        "pr_key": "kubernetes/kubernetes#127490",
        "pr_url": "https://github.com/kubernetes/kubernetes/pull/127490",
        "repo": "kubernetes/kubernetes",
        "pr_number": 127490,
        "title": "Migrate payment reconciliation to use atomic DynamoDB transactions",
        "author": "liggitt",
        "reviewer": "jpbetz",
        "state": "closed",
        "created_at": "2026-09-10T16:00:00Z",
        "merged_at": "2026-09-10T18:05:00Z",
        "change_risk": 0.75,
        "review_confidence": 0.29,
        "residual_risk": 0.53,
        "depth_score": 0.30,
        "attention_state": 0.45,
        "time_adequacy": 0.18,
        "reviewer_familiarity": 0.55,
        "status": "re_queued",
        "re_queued": True,
        "explanation": (
            "A 490-line database transaction migration received only a "
            "clarifying question in 2 minutes from a reviewer 5 reviews into "
            "a session; re-review of the rollback path is recommended."
        ),
        "top_features": [
            {"feature": "path_payment", "contribution": 0.380},
            {"feature": "total_changed_lines", "contribution": 0.270},
            {"feature": "mean_defect_density", "contribution": 0.195},
        ],
        "comments": [
            {"body": "What happens if the conditional write fails halfway?", "class_name": "clarifying", "weight": 0.45, "path": "staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go"},
        ],
        "diff_lines": 490,
        "review_duration_seconds": 118,
        "consecutive_reviews": 5,
        "additions": 380,
        "deletions": 110,
        "changed_files": 6,
        "sensitive_files": [],
        "live": False,
    },
]

BOARD_STATS: dict[str, int | str | float] = {
    "total_scored": 12_847,
    "high_risk_flagged": 412,
    "requeued_today": 38,
    "avg_residual_risk": 0.34,
    "precision_at_5": "4/5",
    "precision_at_10": "7/10",
    "precision_at_20": "9/20",
}

DEFAULT_REPOS: dict[str, dict] = {
    "kubernetes/kubernetes": {
        "full_name": "kubernetes/kubernetes",
        "owner": "kubernetes",
        "repo": "kubernetes",
        "description": "Production-Grade Container Scheduling and Management",
        "stars": "114k",
        "forks": "39.2k",
        "language": "Go",
        "language_color": "#00ADD8",
        "is_public": True,
        "active_prs_count": 88,
        "closed_prs_count": 2975,
        "avg_residual_risk": 0.38,
        "last_fetched_at": "2026-09-17T08:00:00Z",
    },
    "facebook/react": {
        "full_name": "facebook/react",
        "owner": "facebook",
        "repo": "react",
        "description": "The library for web and native user interfaces.",
        "stars": "229k",
        "forks": "46.1k",
        "language": "JavaScript",
        "language_color": "#f1e05a",
        "is_public": True,
        "active_prs_count": 42,
        "closed_prs_count": 14200,
        "avg_residual_risk": 0.41,
        "last_fetched_at": "2026-09-17T08:00:00Z",
    },
    "pallets/flask": {
        "full_name": "pallets/flask",
        "owner": "pallets",
        "repo": "flask",
        "description": "The Python micro framework for building web applications.",
        "stars": "68k",
        "forks": "16.1k",
        "language": "Python",
        "language_color": "#3572A5",
        "is_public": True,
        "active_prs_count": 18,
        "closed_prs_count": 4100,
        "avg_residual_risk": 0.35,
        "last_fetched_at": "2026-09-17T08:00:00Z",
    },
    "django/django": {
        "full_name": "django/django",
        "owner": "django",
        "repo": "django",
        "description": "The Web framework for perfectionists with deadlines.",
        "stars": "81k",
        "forks": "32.4k",
        "language": "Python",
        "language_color": "#3572A5",
        "is_public": True,
        "active_prs_count": 31,
        "closed_prs_count": 16800,
        "avg_residual_risk": 0.39,
        "last_fetched_at": "2026-09-17T08:00:00Z",
    },
    "psf/requests": {
        "full_name": "psf/requests",
        "owner": "psf",
        "repo": "requests",
        "description": "A simple, yet elegant, HTTP library.",
        "stars": "52k",
        "forks": "9.2k",
        "language": "Python",
        "language_color": "#3572A5",
        "is_public": True,
        "active_prs_count": 12,
        "closed_prs_count": 3900,
        "avg_residual_risk": 0.32,
        "last_fetched_at": "2026-09-17T08:00:00Z",
    },
}

