"""
Vouch — Change-risk feature vector extraction.

Computes all features needed by Model 1 (Change Risk) from:
  - The raw diff stored in S3
  - The pre-computed file history table in DynamoDB (vouch-files)
  - The PR metadata already stored in vouch-prs

Triggered by EventBridge PRIngested events.
"""

from __future__ import annotations

import json
import logging
import math
import os
import re
import time
from typing import Any

import boto3

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

_dynamodb = boto3.resource("dynamodb")
_s3 = boto3.client("s3")
_eventbridge = boto3.client("events")

PRS_TABLE = os.environ.get("PRS_TABLE", "vouch-prs-dev")
FILES_TABLE = os.environ.get("FILES_TABLE", "vouch-files-dev")
RAW_BUCKET = os.environ.get("RAW_BUCKET", "vouch-raw")
EVENT_BUS_NAME = os.environ.get("EVENT_BUS_NAME", "vouch-events-dev")

# ── Path sensitivity regexes ──────────────────────────────────────────────────

SENSITIVE_PATHS = {
    "auth": re.compile(r"(auth|authn|authz|oauth|jwt|token|session|login|sso|saml|ldap)", re.I),
    "payment": re.compile(r"(payment|billing|stripe|invoice|charge|wallet|pci|checkout|cart)", re.I),
    "migration": re.compile(r"(migration|migrate|schema|alembic|flyway|liquibase|alter_table)", re.I),
    "crypto": re.compile(r"(crypto|encrypt|decrypt|cipher|hash|secret|key|vault|kms|hsm|tls|ssl|cert)", re.I),
    "config": re.compile(r"(config|settings|env|\.env|environment|properties|constants)", re.I),
    "infra": re.compile(r"(terraform|cloudformation|helm|k8s|kubernetes|docker|compose|dockerfile|ecs|eks)", re.I),
    # New categories
    "audit": re.compile(r"(audit|compliance|gdpr|ccpa|pci|soc2|hipaa|regulation|policy)", re.I),
    "credentials": re.compile(r"(password|passwd|creds|credentials|private.?key|api.?key|access.?key|service.?account)", re.I),
    "iac": re.compile(r"(pulumi|ansible|chef|puppet|salt|cdk|bicep|sam\.yaml|serverless\.yml)", re.I),
    "testing": re.compile(r"(test|spec|fixture|mock|stub|factory|seed)", re.I),
}

# ── AI authorship signals ─────────────────────────────────────────────────────

AI_COMMIT_PATTERNS = re.compile(
    r"(co-authored-by: github-actions|generated by|copilot|cursor|claude|chatgpt|gpt-4|gpt4|"
    r"gemini|devin|aider|sweep|cody|tabnine|kite|codewhisperer|continue\.dev|ai-generated|"
    r"autocomplete|auto-generated|llm|openai)",
    re.I,
)


# ─────────────────────────────────────────────────────────────────────────────
# Feature extraction
# ─────────────────────────────────────────────────────────────────────────────

def extract_diff_features(diff_text: str) -> dict:
    """Extract features from raw diff text."""
    lines = diff_text.splitlines()
    added = sum(1 for l in lines if l.startswith("+") and not l.startswith("+++"))
    removed = sum(1 for l in lines if l.startswith("-") and not l.startswith("---"))

    # Count file headers
    file_headers = [l for l in lines if l.startswith("diff --git")]
    files_touched = len(file_headers)

    # Count hunks
    hunks = sum(1 for l in lines if l.startswith("@@"))
    max_hunk_size = _max_hunk_size(lines)

    return {
        "lines_added": added,
        "lines_removed": removed,
        "net_delta": added - removed,
        "total_changed_lines": added + removed,
        "files_touched": files_touched,
        "hunk_count": hunks,
        "max_hunk_size": max_hunk_size,
    }


def _max_hunk_size(lines: list[str]) -> int:
    """Return the size (in changed lines) of the largest hunk."""
    max_size = 0
    current = 0
    for line in lines:
        if line.startswith("@@"):
            max_size = max(max_size, current)
            current = 0
        elif line.startswith(("+", "-")) and not line.startswith(("+++", "---")):
            current += 1
    return max(max_size, current)


def extract_path_features(file_paths: list[str]) -> dict:
    """Flag whether the diff touches any sensitive file categories."""
    flags: dict[str, int] = {k: 0 for k in SENSITIVE_PATHS}
    for path in file_paths:
        for category, pattern in SENSITIVE_PATHS.items():
            if pattern.search(path):
                flags[category] = 1
    flags["sensitive_path_count"] = sum(flags.values())
    return {f"path_{k}": v for k, v in flags.items()}


def extract_ai_authorship_features(commit_message: str, diff_text: str) -> dict:
    """Heuristic signals that a change was AI-authored."""
    ai_commit = int(bool(AI_COMMIT_PATTERNS.search(commit_message)))
    # Also scan the diff body itself for AI tool markers
    ai_in_diff = int(bool(AI_COMMIT_PATTERNS.search(diff_text[:2000])))
    ai_commit_signal = max(ai_commit, ai_in_diff)

    # Diff-shape heuristic: very uniform line lengths typical of LLM output
    lines = [l for l in diff_text.splitlines()
             if l.startswith("+") and not l.startswith("+++")]
    if len(lines) > 10:
        lengths = [len(l) for l in lines]
        mean_len = sum(lengths) / len(lengths)
        variance = sum((x - mean_len) ** 2 for x in lengths) / len(lengths)
        uniformity = 1.0 / (1.0 + math.sqrt(variance))
    else:
        uniformity = 0.5

    # Block-add heuristic: many lines added in a single hunk (common LLM pattern)
    hunks = diff_text.count("\n@@")
    block_ratio = round(len(lines) / max(hunks, 1) / 50.0, 4)  # > 1.0 = large blocks
    block_add_signal = min(block_ratio, 1.0)

    return {
        "ai_commit_signal": ai_commit_signal,
        "diff_uniformity": round(uniformity, 4),
        "block_add_signal": round(block_add_signal, 4),
    }


def get_file_history_features(org: str, repo: str, file_paths: list[str]) -> dict:
    """
    Look up pre-computed file history from DynamoDB.
    Falls back to zeros if a file is not yet in the table.
    """
    table = _dynamodb.Table(FILES_TABLE)
    total_churn = 0
    total_reverts = 0
    total_defect_density = 0.0
    ownership_ginis = []

    for path in file_paths[:20]:  # cap to avoid excessive reads
        pk = f"{org}/{repo}#{path}"
        resp = table.get_item(Key={"pk": pk})
        item = resp.get("Item", {})
        total_churn += item.get("churn_90d", 0)
        total_reverts += item.get("revert_count", 0)
        total_defect_density += float(item.get("defect_density", 0.0))
        ownership_ginis.append(float(item.get("ownership_gini", 0.5)))

    n = max(len(file_paths), 1)
    return {
        "total_churn_90d": total_churn,
        "total_revert_count": total_reverts,
        "mean_defect_density": round(total_defect_density / n, 4),
        "mean_ownership_gini": round(sum(ownership_ginis) / max(len(ownership_ginis), 1), 4),
    }


def compute_feature_vector(
    org: str,
    repo: str,
    pr_meta: dict,
    diff_text: str,
    commit_message: str = "",
    pr_body: str = "",
    pr_created_at: str = "",
    pr_merged_at: str = "",
) -> dict:
    """Compose the full change-risk feature vector."""
    import time as _time
    from datetime import datetime as _dt, timezone as _tz

    file_paths = pr_meta.get("file_paths", [])

    features: dict = {}
    features.update(extract_diff_features(diff_text))
    features.update(extract_path_features(file_paths))
    features.update(extract_ai_authorship_features(commit_message, diff_text))
    features.update(get_file_history_features(org, repo, file_paths))

    # Author tenure (from PR meta, populated by corpus miner)
    features["author_prior_commits_in_files"] = pr_meta.get("author_prior_commits", 0)

    # PR description quality: 0.0 (empty) → 1.0 (well-described)
    body_len = len((pr_body or "").strip())
    features["pr_description_quality"] = round(min(body_len / 300.0, 1.0), 4)

    # Rapid merge signal: merged < 600 seconds after opening
    rapid_merge = 0
    if pr_created_at and pr_merged_at:
        try:
            t0 = _dt.fromisoformat(pr_created_at.replace("Z", "+00:00"))
            t1 = _dt.fromisoformat(pr_merged_at.replace("Z", "+00:00"))
            merge_secs = (t1 - t0).total_seconds()
            rapid_merge = 1 if merge_secs < 600 else 0
        except Exception:
            pass
    features["rapid_merge_signal"] = rapid_merge

    return features


# ─────────────────────────────────────────────────────────────────────────────
# Lambda handler
# ─────────────────────────────────────────────────────────────────────────────

def lambda_handler(event: dict, context: Any) -> dict:
    """Triggered by EventBridge PRIngested — extracts features and stores them."""
    detail = event.get("detail", event)
    pr_key = detail["pr_key"]
    org = detail["org"]
    repo = detail["repo"]
    pr_number = detail["pr_number"]

    # Fetch PR metadata
    prs_table = _dynamodb.Table(PRS_TABLE)
    pr_item = prs_table.get_item(Key={"pk": pr_key}).get("Item", {})

    # Fetch raw diff from S3
    s3_key = f"raw/{org}/{repo}/{pr_number}/diff.patch"
    try:
        diff_obj = _s3.get_object(Bucket=RAW_BUCKET, Key=s3_key)
        diff_text = diff_obj["Body"].read().decode("utf-8", errors="replace")
    except _s3.exceptions.NoSuchKey:
        diff_text = ""
        logger.warning("No diff found at %s", s3_key)

    feature_vector = compute_feature_vector(
        org=org,
        repo=repo,
        pr_meta=pr_item,
        diff_text=diff_text,
        commit_message=pr_item.get("commit_message", ""),
    )

    # Write features back to the PR record
    prs_table.update_item(
        Key={"pk": pr_key},
        UpdateExpression="SET features = :f, features_extracted_at = :t",
        ExpressionAttributeValues={
            ":f": feature_vector,
            ":t": int(time.time()),
        },
    )

    # Emit FeaturesExtracted for the scoring pipeline to pick up
    _eventbridge.put_events(
        Entries=[
            {
                "Source": "vouch.features",
                "DetailType": "FeaturesExtracted",
                "Detail": json.dumps({"pr_key": pr_key, "org": org, "repo": repo}),
                "EventBusName": EVENT_BUS_NAME,
            }
        ]
    )

    logger.info("Features extracted for %s: %s", pr_key, feature_vector)
    return {"pr_key": pr_key, "feature_count": len(feature_vector)}
