"""
Tests for features/extractor.py — diff and repository feature engineering.
"""

import pytest

from features.extractor import (
    _max_hunk_size,
    extract_ai_authorship_features,
    extract_diff_features,
    extract_path_features,
)


class TestDiffFeatureExtraction:
    def test_extract_diff_features_from_sample(self, sample_diff):
        feats = extract_diff_features(sample_diff)

        # In sample_diff:
        # auth/jwt.py: -1, +3
        # config/settings.yaml: +1
        # Total added = 4, removed = 1, delta = 3, total = 5
        # 2 files touched, 2 hunks (@@)
        assert feats["lines_added"] == 4
        assert feats["lines_removed"] == 1
        assert feats["net_delta"] == 3
        assert feats["total_changed_lines"] == 5
        assert feats["files_touched"] == 2
        assert feats["hunk_count"] == 2
        assert feats["max_hunk_size"] >= 1

    def test_empty_diff_returns_zeros(self):
        feats = extract_diff_features("")
        assert feats["lines_added"] == 0
        assert feats["lines_removed"] == 0
        assert feats["net_delta"] == 0
        assert feats["total_changed_lines"] == 0
        assert feats["files_touched"] == 0
        assert feats["hunk_count"] == 0
        assert feats["max_hunk_size"] == 0

    def test_max_hunk_size_calculation(self):
        lines = [
            "@@ -1,5 +1,5 @@",
            "+one",
            "+two",
            "-three",
            "@@ -10,3 +10,4 @@",
            "+four",
        ]
        # First hunk has 3 changed lines (+, +, -), second hunk has 1 (+)
        assert _max_hunk_size(lines) == 3


class TestSensitivePathFeatures:
    def test_sensitive_path_detection(self):
        paths = [
            "src/auth/jwt.py",
            "db/migrations/001_init.sql",
            "k8s/deployment.yaml",
            "docs/README.md",
        ]
        path_feats = extract_path_features(paths)
        assert path_feats["path_auth"] == 1
        assert path_feats["path_migration"] == 1
        assert path_feats["path_infra"] == 1
        assert path_feats["path_payment"] == 0
        assert path_feats["path_crypto"] == 0

    def test_harmless_paths(self):
        paths = ["README.md", "assets/logo.png", "src/components/button.tsx"]
        path_feats = extract_path_features(paths)
        for key, val in path_feats.items():
            assert val == 0


class TestAiAuthorshipFeatures:
    def test_ai_commit_signal_detection(self):
        res1 = extract_ai_authorship_features("Refactor auth logic (generated by copilot)", "")
        assert res1["ai_commit_signal"] == 1

        res2 = extract_ai_authorship_features("Co-authored-by: github-actions[bot]", "")
        assert res2["ai_commit_signal"] == 1

        res3 = extract_ai_authorship_features("Fix typo using ChatGPT", "")
        assert res3["ai_commit_signal"] == 1

        res4 = extract_ai_authorship_features("Claude prompt engineering", "")
        assert res4["ai_commit_signal"] == 1

    def test_human_commit_signal(self):
        res = extract_ai_authorship_features("Manual fix for race condition in worker", "")
        assert res["ai_commit_signal"] == 0

    def test_diff_uniformity_computation(self):
        res_empty = extract_ai_authorship_features("Human commit", "")
        assert res_empty["diff_uniformity"] == 0.5

        # 15 lines of identical length
        uniform_diff = "\n".join(["+1234567890"] * 15)
        res_uniform = extract_ai_authorship_features("Human commit", uniform_diff)
        assert res_uniform["diff_uniformity"] == 1.0

